sudo: required
services:
  - docker

before_install:
  - docker build -t arseniypanfilov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arseniypanfilov/react-test npm test

after_success:
  - docker build -t arseniypanfilov/multi-client ./client
  - docker build -t arseniypanfilov/multi-nginx ./nginx
  - docker build -t arseniypanfilov/multi-server ./server
  - docker build -t arseniypanfilov/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the images and push to docker hub
  - docker push arseniypanfilov/multi-client
  - docker push arseniypanfilov/multi-nginx
  - docker push arseniypanfilov/multi-server
  - docker push arseniypanfilov/multi-worker
